from __future__ import annotations
import pytest

pytestmark = pytest.mark.skip(reason="Wave 1-2 implements — skeleton only")


def test_vault01_cli_does_not_overwrite_foreign(tmp_path): ...
def test_vault01_write_decision_table(tmp_path): ...
def test_vault02_frontmatter_has_required_fields(tmp_path): ...
def test_vault02_frontmatter_tags_namespaces(tmp_path): ...
def test_vault03_things_dispatch(tmp_path): ...
def test_vault03_questions_always_promoted(tmp_path): ...
def test_vault03_maps_moc_frontmatter(tmp_path): ...
def test_vault04_related_extracted_only(tmp_path): ...
def test_vault05_import_log_written(tmp_path): ...
def test_vault05_import_log_append_latest_first(tmp_path): ...
def test_vault06_profile_writeback_union_merge(tmp_path): ...
def test_vault06_profile_writeback_opt_out(tmp_path): ...
def test_vault07_tag_taxonomy_layer_merge(tmp_path): ...
